services:
  api:
    build: .
    image: app-api-makeup/api
    restart: on-failure
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 8080 --proxy-headers
    volumes:
      - ./:/opt/python-projects/app/
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ./env/app.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://127.0.0.1:8080/v1/home/ping || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      mgdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 3

  mgdb:
    image: mongo
    restart: on-failure
    volumes:
      - ./mongo:/data/db
    command: --quiet
    ports:
      - "127.0.0.1:27019:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6